# Generated by Django 3.2.16 on 2024-04-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0002_auto_20221226_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(default='A monster', max_length=100, verbose_name='Name'),
        ),
    ]
