# Generated by Django 3.2.16 on 2024-04-02 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0003_alter_monster_name'),
        ('battle', '0002_auto_20240401_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='monsterA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battlesA', to='monster.monster'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='monsterB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battlesB', to='monster.monster'),
        ),
    ]
